# Generated by Django 4.1.5 on 2023-02-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
