# Generated by Django 4.1.5 on 2023-02-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_fans_blogger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fans_Blogger',
        ),
    ]
