# Generated by Django 4.1.5 on 2023-02-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_fans_blogger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fans_Blog',
        ),
    ]
