# Generated by Django 4.1.5 on 2023-02-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_delete_fans_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fans_blogger',
            name='Blog',
        ),
        migrations.AddField(
            model_name='fans_blogger',
            name='Blogger',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userinfo_Blogger', to='app01.userinfo', verbose_name='回复用户关联_id'),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=128, null=True, verbose_name='消息内容')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='类型')),
                ('time_TS', models.CharField(blank=True, max_length=128, null=True, verbose_name='时间标志位')),
                ('create_time', models.DateTimeField(blank=True, default=0, max_length=128, null=True, verbose_name='发布时间')),
                ('read', models.CharField(blank=True, default='False', max_length=164, null=True, verbose_name='已读回执')),
                ('re_user', models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mess_reuser', to='app01.userinfo', verbose_name='回复用户关联_id')),
                ('user', models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mess_user', to='app01.userinfo', verbose_name='用户关联_id')),
            ],
        ),
    ]
