# Generated by Django 4.1.5 on 2023-02-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_remove_fans_blogger_blog_fans_blogger_blogger_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail_viewer',
            new_name='Detail_viewer1',
        ),
    ]
