# Generated by Django 4.1.5 on 2023-02-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_rename_detail_viewer_detail_viewer1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail_viewer1',
            new_name='Detail_viewer',
        ),
    ]
