# Generated by Django 4.1.5 on 2023-02-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_rename_detail_viewer1_detail_viewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail_viewer',
        ),
    ]
