# Generated by Django 4.1.5 on 2023-02-24 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_delete_detail_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_TS', models.CharField(blank=True, max_length=32, null=True, verbose_name='根新闻TS')),
                ('news_ustu', models.CharField(blank=True, max_length=32, null=True, verbose_name='根新闻stu')),
                ('create_time', models.DateTimeField(blank=True, max_length=128, null=True, verbose_name='发布时间')),
                ('time_TS', models.CharField(blank=True, max_length=128, null=True, verbose_name='时间标志位')),
                ('user', models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo', verbose_name='用户关联_id')),
            ],
        ),
    ]
