# Generated by Django 4.1.5 on 2023-02-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_detail_viewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_favor',
        ),
    ]
