# Generated by Django 4.1.5 on 2023-02-24 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_delete_comment_favor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_TS', models.CharField(blank=True, max_length=32, null=True, verbose_name='根新闻TS')),
                ('news_ustu', models.CharField(blank=True, max_length=32, null=True, verbose_name='根新闻stu')),
                ('depth', models.CharField(blank=True, max_length=32, null=True, verbose_name='评论等级')),
                ('comment_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='根评论id')),
                ('time_TS', models.CharField(blank=True, max_length=128, null=True, verbose_name='时间标志位')),
                ('create_time', models.DateTimeField(blank=True, max_length=128, null=True, verbose_name='发布时间')),
                ('yes_or_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='根新闻stu')),
                ('whether_read', models.CharField(blank=True, max_length=32, null=True, verbose_name='根新闻stu')),
                ('user', models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo', verbose_name='用户关联_id')),
            ],
        ),
    ]
