# Generated by Django 4.1.5 on 2023-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_comment_favor'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(blank=True, default='False', max_length=164, null=True, verbose_name='已读回执')),
                ('member', models.CharField(blank=True, default='False', max_length=164, null=True, verbose_name='已读回执')),
            ],
        ),
        migrations.AddField(
            model_name='commentrecord',
            name='read',
            field=models.CharField(blank=True, default='False', max_length=164, null=True, verbose_name='已读回执'),
        ),
        migrations.AddField(
            model_name='message',
            name='room_num',
            field=models.CharField(blank=True, default='False', max_length=164, null=True, verbose_name='已读回执'),
        ),
    ]
