# Generated by Django 4.1.5 on 2023-02-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_room_commentrecord_read_message_room_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmessage',
            name='heat_num',
            field=models.PositiveIntegerField(default=0, verbose_name='热度'),
        ),
    ]
